
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-kubeflow-user-workspace
  labels:
    service-pvname: service-kubeflow-user-workspace
spec:
  storageClassName: local-storage
#  storageClassName: pipeline
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: service
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      service-pvname: service-kubeflow-user-workspace


# 模型归档
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: service-kubeflow-archives
  labels:
    service-pvname: service-kubeflow-archives
spec:
  storageClassName: local-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/archives
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-archives
  namespace: service
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      service-pvname: service-kubeflow-archives


