# 训练调用需要
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-global-pv
  labels:
    pipeline-pvname: pipeline-kubeflow-global-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/global
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-global-pvc
  namespace: pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pipeline-pvname: pipeline-kubeflow-global-pv


# 模型训练
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-user-workspace
  labels:
    pipeline-pvname: pipeline-kubeflow-user-workspace
spec:
  storageClassName: local-storage
#  storageClassName: pipeline
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pipeline-pvname: pipeline-kubeflow-user-workspace
# 模型部署
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-model-deploy
  labels:
    pipeline-pvname: pipeline-model-deploy
spec:
  storageClassName: local-storage
#  storageClassName: pipeline
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ceph_fuse/meiyangchen
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-model-deploy
  namespace: pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      pipeline-pvname: pipeline-model-deploy

# 模型归档
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-kubeflow-archives
  labels:
    pipeline-pvname: pipeline-kubeflow-archives
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/archives
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-archives
  namespace: pipeline
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pipeline-pvname: pipeline-kubeflow-archives



