

# 模型训练
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-kubeflow-user-workspace
  labels:
    kubeflow-pvname: kubeflow-kubeflow-user-workspace
spec:
  storageClassName: local-storage
#  storageClassName: pipeline
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/k8s/kubeflow/pipeline/workspace
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-user-workspace
  namespace: kubeflow
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      kubeflow-pvname: kubeflow-kubeflow-user-workspace
