---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv
  labels:
    infra-pvname: infra-mysql-pv
spec:
  storageClassName: local-storage
  capacity:       
    storage: 5Gi
  accessModes:   
    - ReadWriteMany   
  hostPath:
    path: /data/k8s/infra/mysql
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: infra-mysql-pvc
  namespace: infra
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      infra-pvname: infra-mysql-pv



