---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-minio-pv
  labels:
    kubeflow-pvname: kubeflow-minio-pv
spec:
  storageClassName: local-storage
  capacity:       
    storage: 8Gi
  accessModes:   
    - ReadWriteOnce   
  hostPath:
    path: /data/k8s/kubeflow/minio
  persistentVolumeReclaimPolicy: Retain

  